### ISSUE TITLE
`use_description(fields = list(Package = "validname")))` uses default name to check_name

### ISSUE THREAD

**Issue by Bisaloo** [r-lib/usethis#1675] opened 2022-09-14 08:15 UTC
``` r
tf <- tempfile("unvalid_package_name")

dir.create(tf)

usethis::proj_set(tf, force = TRUE)
#> ✔ Setting active project to '/tmp/RtmpBkQGCz/unvalid_package_name2acb5238031c'
usethis::use_description(fields = list(Package = "validname"))
#> Error: 'unvalid_package_name2acb5238031c' is not a valid package name. To be allowed on CRAN, it should:
#> * Contain only ASCII letters, numbers, and '.'
#> * Have at least two characters
#> * Start with a letter
#> * Not end with '.'
```

<sup>Created on 2022-09-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

I'm in a project whose name would not be a valid package name (this is for a reprex package, I realise this would not be ideal for an actual package). To work around this, I'm overriding the package name with a valid name but it looks like the name checking step takes place before taking this into account.

**Comment by jennybc** [comment] 2022-09-14 19:51
Duplicate of #1651

**Closed by jennybc** 2022-09-14 19:51 UTC
