### ISSUE TITLE
Shouldn't `use_article()` place files in `vignettes/articles`?

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/usethis#1202] opened 2020-08-06 15:19 UTC
```r
> usethis::use_article("gotchas", "Common Gotchas")
✓ Setting active project to '/Users/davis/Desktop/r/packages/furrr'
✓ Writing 'vignettes/gotchas.Rmd'
● Modify 'vignettes/gotchas.Rmd'
```

It sets up a build ignore on `vignettes/articles`, but articles are just placed in `vignettes/`

```r
function (name, title = name) 
{
    check_is_package("use_article()")
    path <- use_vignette_template("article.Rmd", name, title)
    use_build_ignore("vignettes/articles")
    invisible()
}
```

**Comment by jennybc** [comment] 2020-08-06 17:39
Duplicate of https://github.com/r-lib/usethis/issues/548

**Closed by jennybc** 2020-08-06 17:39 UTC
