### ISSUE TITLE
Can't fetch PR if only remote is upstream

### ISSUE THREAD

**Issue by karawoo** [r-lib/usethis#1006] opened 2020-02-03 22:47 UTC
I'm seeing an error when I try to `pr_fetch()` a PR to a remote repo that I have called `upstream`. The documentation makes it sound like this should be fine:

```
owner: Name of the owner of the repository that is the target of the
       pull request. Default of NULL tries to identify the source
       repo and uses the owner of the ‘upstream’ remote, if present,
       or the owner of ‘origin’ otherwise.
```

However `pr_fetch()` throws an error:

```r
pr_fetch(42)
#> Error: This project does not have a GitHub remote configured as 'origin'.
#> Do you need to run `use_github()`?

pr_fetch(42, owner = "Sage-Bionetworks")
#> Error: This project does not have a GitHub remote configured as 'origin'.
#> Do you need to run `use_github()`?
```
<sup>
(not sure the best way to provide a reprex of my local git setup, but hopefully this is clear enough!)</sup>

I do not have a remote called `origin`. If it matters, my habit with work projects is to call whatever is in github.com/\<workplace-org\> `upstream`, and if I fork it into my personal github, to call that `origin`. In this case I have not forked the project, so I only have the upstream remote. 

The first step in `pr_fetch()`, `check_uses_github()`, looks specifically for remotes called `origin`, but from the `pr_fetch()` docs it doesn't sound like `origin` is required. Would it be possible to make this check a little more flexible to accommodate other remotes (or at least `upstream`)? Or do I just need to fork this repo or rename my remote?

**Comment by hadley** [comment] 2020-03-14 14:47
Do you want to try a PR for this? Looking at the code, I think the problem is the call to `github_repo()`, which looks at origin. I think you just need to do something similar to the previous line:

```R
owner <- owner %||% github_owner_upstream() %||% github_owner()
```

**Comment by hadley** [comment] 2020-03-14 14:48
Or possibly it's better to fix this more generally along the lines of #838

**Comment by karawoo** [comment] 2020-03-14 18:31
Yes I'm happy to work on this (will probably be a few weeks as I'm in the middle of a move)

**Comment by jennybc** [comment] 2020-07-04 05:10
I'm afraid that the changes coming in #1144 mean this has become a #wontfix. As documented there, the `pr_*()` functions are ready to handle exactly two GitHub remote configurations: "ours" and "fork". More details here:

https://happygitwithr.com/common-remote-setups.html

The complexity of handling all possible remote conventions does not seem justified, so I've settled on those that are most common.

**Closed by jennybc** 2020-07-04 05:10 UTC
Labels: bug, git
