### ISSUE TITLE
.github/CODE_OF_CONDUCT.md is a possibly invalid file URL

### ISSUE THREAD

**Issue by jmgirard** [r-lib/usethis#877] opened 2019-08-21 13:48 UTC
The `use_tidy_coc()` function adds a link to `.github/CODE_OF_CONDUCT.md` to `README.md`. However, this now triggers a NOTE on CRAN check and prevents CRAN acceptance:
```
* checking CRAN incoming feasibility ... NOTE
Found the following (possibly) invalid file URI:
  URI: .github/CODE_OF_CONDUCT.md
    From: README.md
```
From CRAN manual inspection:
> Please replace by a fully specified URL. Please fix and resubmit.

So it looks like this kind of relative URL may no longer be accepted by CRAN check.

**Comment by jennybc** [comment] 2019-08-21 14:47
Duplicate of #772

**Closed by jennybc** 2019-08-21 14:47 UTC
