### ISSUE TITLE
use_git() results in "Error in path.expand(path) : invalid 'path' argument"

### ISSUE THREAD

**Issue by alexholcombe** [r-lib/usethis#128] opened 2017-12-06 18:44 UTC
```
> use_git()
✔ Initialising Git repo
✔ Adding '.Rhistory', '.RData' to './.gitignore'
✔ Adding files and committing
Error in path.expand(path) : invalid 'path' argument
```
This is with usethis v1.1.0 on OSX with RStudio 1.1.383 and R 3.4.2.  create_package did succeed, and the package directory is a subdirectory of RStudio's current working directory. 

Please let me know if I should provide additional info or this is not the best place to ask about this.

**Comment by jennybc** [comment] 2017-12-19 06:19
I can't reproduce this. Can you? If so, what is the actual path? What paths does `git status` in the shell show at this point for this repo?

**Comment by jennybc** [comment] 2018-01-03 18:28
Last call for more info before I close this ... I'll give it a couple more days.

**Comment by muschellij2** [comment] 2018-03-27 18:38
I can reproduce but only under an interactive session interactive.  I have some `setwd` in there to replicate, but I wouldn't assume people would need to use things this way.

## Interactive Error 

If I run this in RStudio interactively (`template` folder must not exist):

```r
setwd("~/Desktop/")
pkgname = "template"
devtools::create(pkgname)
setwd(pkgname)
usethis::use_git()
```

I get the error:
```
✔ Initialising Git repo
✔ Adding files and committing
Error in path.expand(path) : invalid 'path' argument
```

Similarly:
```r
wd = "~/"
wd = path.expand(wd)
print(wd)
#> [1] "/Users/johnmuschelli/"
setwd(wd)
dir.exists(wd)
#> [1] TRUE
pkgname = "template"
devtools::create(pkgname)
dir.exists(pkgname)
#> [1] TRUE
setwd(pkgname)
```
and then running:
```r
usethis::use_git()
```
returns 
```
✔ Initialising Git repo
Error in normalizePath(path, winslash = "/", mustWork = TRUE) : 
  path[1]="/Users/johnmuschelli/Desktop/template": No such file or directory
In addition: Warning message:
In normalizePath(path) :
  path[1]="/Users/johnmuschelli/Desktop/template": No such file or directory
```

## Conditions with no error
But when using `reprex`, I don't get any error 


```r
wd = "~/"
wd = path.expand(wd)
print(wd)
#> [1] "/Users/johnmuschelli/"
setwd(wd)
dir.exists(wd)
#> [1] TRUE
pkgname = "template"
devtools::create(pkgname)
#> Creating package 'template' in '/Users/johnmuschelli'
#> No DESCRIPTION found. Creating with values:
#> Package: template
#> Title: What the Package Does (one line, title case)
#> Version: 0.0.0.9000
#> Authors@R: person("First", "Last", email = "first.last@example.com", role = c("aut", "cre"))
#> Description: What the package does (one paragraph).
#> Depends: R (>= 3.4.4)
#> License: What license is it under?
#> Encoding: UTF-8
#> LazyData: true
#> * Creating `template.Rproj` from template.
#> * Adding `.Rproj.user`, `.Rhistory`, `.RData` to ./.gitignore
dir.exists(pkgname)
#> [1] TRUE
setwd(pkgname)
usethis::use_git()
#> ✔ Initialising Git repo
#> ✔ Adding files and committing
```

## Session Info
```r
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.4.4 (2018-03-15)
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  tz       America/New_York            
#>  date     2018-03-27
#> Packages -----------------------------------------------------------------
#>  package    * version    date      
#>  backports    1.1.2      2017-12-13
#>  base       * 3.4.4      2018-03-15
#>  clisymbols   1.2.0      2018-03-27
#>  compiler     3.4.4      2018-03-15
#>  crayon       1.3.4      2018-03-27
#>  datasets   * 3.4.4      2018-03-15
#>  devtools     1.13.5     2018-02-18
#>  digest       0.6.15     2018-01-28
#>  evaluate     0.10.1     2017-06-24
#>  git2r        0.21.0     2018-01-04
#>  graphics   * 3.4.4      2018-03-15
#>  grDevices  * 3.4.4      2018-03-15
#>  htmltools    0.3.6      2017-04-28
#>  knitr        1.20       2018-02-20
#>  magrittr     1.5        2014-11-22
#>  memoise      1.1.0      2017-04-21
#>  methods    * 3.4.4      2018-03-15
#>  Rcpp         0.12.16    2018-03-13
#>  rmarkdown    1.9        2018-03-01
#>  rprojroot    1.3-2      2018-01-03
#>  rstudioapi   0.7        2017-09-07
#>  stats      * 3.4.4      2018-03-15
#>  stringi      1.1.7      2018-03-12
#>  stringr      1.3.0      2018-02-19
#>  tools        3.4.4      2018-03-15
#>  usethis      1.3.0.9000 2018-03-27
#>  utils      * 3.4.4      2018-03-15
#>  whisker      0.3-2      2013-04-28
#>  withr        2.1.2      2018-03-15
#>  yaml         2.1.18     2018-03-08
#>  source                                 
#>  CRAN (R 3.4.3)                         
#>  local                                  
#>  Github (gaborcsardi/clisymbols@e49b4f5)
#>  local                                  
#>  Github (gaborcsardi/crayon@95b3eae)    
#>  local                                  
#>  CRAN (R 3.4.3)                         
#>  CRAN (R 3.4.3)                         
#>  cran (@0.10.1)                         
#>  CRAN (R 3.4.3)                         
#>  local                                  
#>  local                                  
#>  CRAN (R 3.4.0)                         
#>  CRAN (R 3.4.3)                         
#>  CRAN (R 3.4.0)                         
#>  CRAN (R 3.4.0)                         
#>  local                                  
#>  CRAN (R 3.4.4)                         
#>  CRAN (R 3.4.3)                         
#>  cran (@1.3-2)                          
#>  CRAN (R 3.4.1)                         
#>  local                                  
#>  CRAN (R 3.4.4)                         
#>  cran (@1.3.0)                          
#>  local                                  
#>  local                                  
#>  local                                  
#>  CRAN (R 3.4.0)                         
#>  CRAN (R 3.4.3)                         
#>  CRAN (R 3.4.4)
```

**Comment by jennybc** [comment] 2018-03-27 19:39
I can't read/digest this right this moment but looks like I should re-open.

**Comment by jennybc** [comment] 2018-05-22 16:41
Reading more carefully, I suspect this results from the "current project" of usethis != current working directory. I'm going to close again. But please open a new issue if the problem persists and it can be shown that usethis is targeting the correct directory in `use_git()`. The function `usethis::proj_get()` will reveal the current project. If this saga continues, it would be helpful to also report the version of git2r.

**Closed by jennybc** 2018-05-22 16:41 UTC
