### ISSUE TITLE
Package-level documentation alias collides with others without warning

### ISSUE THREAD

**Issue by netique** [r-lib/usethis#1320] opened 2020-12-27 13:39 UTC
When user wants to build package-level documentation page and there is a function with the same name (which could be quite common), `roxygen2` generates two .Rd pages with the same `\alias`es. This could be a foundation of many problems (see issues https://github.com/r-lib/pkgdown/issues/1459 and https://github.com/r-lib/downlit/issues/73 for real-life reference).

```r
usethis::use_package_doc()
```

I do not know how to solve it, but a user should be warned at least of possible consequences. There could be option to use different alias as well.

**Comment by jennybc** [comment] 2020-12-28 17:01
Duplicate of #1170, which concludes the best place the address this definitely is in roxygen2

**Closed by jennybc** 2020-12-28 17:01 UTC
