### ISSUE TITLE
pr_finish() and multiple PRs

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#1486] opened 2021-09-17 14:14 UTC
Recently I've been hitting this:

```R
pr_finish()
#> Error: Branch 'max-fails' is associated with multiple PRs: '#1453', '#1069'
```

I thought we were locally caching the PR number associated with each branch?

**Comment by jennybc** [comment] 2021-09-17 14:22
I suspect this is a duplicate of #1449

**Closed** 2021-09-17 15:51 UTC
