### ISSUE TITLE
Weird behavior when creating a package from a vignette

### ISSUE THREAD

**Issue by maelle** [r-lib/usethis#1504] opened 2021-10-01 11:19 UTC
I found weird behavior of pkgdown (or something else?): https://maelle.github.io/wat/articles/ok.html + https://github.com/maelle/wat
- the website uses pkgdown dev version.
- the vignette creates a package in a temporary directory using usethis. 
- the DESCRIPTION of that created package is mangled.
- this mangling does not happen when running the code directly nor when knitting the vignette.

**Comment by hadley** [comment] 2021-10-01 22:08
Yeah, I've transferred to usethis for investigation there

**Comment by jennybc** [comment] 2021-10-01 23:34
So you folks think this is a usethis problem, not a desc problem?

**Comment by jennybc** [comment] 2021-10-01 23:39
Because I **am** specifying `mode = "file"`:

https://github.com/r-lib/usethis/blob/1f6bff8e308d5821b8814d3bab2cda77100fd8e6/R/description.R#L67

**Comment by maelle** [comment] 2021-10-02 05:48
@jennybc since https://github.com/r-lib/usethis/issues/1504#issuecomment-932203563 I do wonder whether it's a desc problem indeed i.e. I'd expect desc to strip the formatting of all fields with that mode but it doesn't.

I was about to ask why usethis doesn't use a desc `write()` method but I suppose it's to be able to use `write_over()`.

**Comment by jennybc** [comment] 2021-10-02 16:35
cc @gaborcsardi

**Comment by gaborcsardi** [comment] 2021-10-04 12:38
Yes, I am fairly sure that I did not mean writing the output of `str()` to file, but of course I understand why you would think the opposite with `mode = "file"`.

In any case `$write()` is better, because it takes care of a couple of things that are different when writing to a file. E.g. it carefully keeps the encoding correct, even if the encoding of the session and the encoding of the file are different; it makes sure that the trailing spaces after the `:` are the same as in the original file to avoid spurious changes, etc.

**Comment by jennybc** [comment] 2021-10-04 15:37
I guess I need to write to a temporary file in order to still run this through `write_over()`.

**Comment by gaborcsardi** [comment] 2021-10-04 15:50
Yeah, or you can temporarily set `options(cli.num_colors = 1)`.

**Comment by gaborcsardi** [comment] 2021-10-04 15:52
Oh, probably you can write to a connection as well, maybe that's simpler than a temporary file.

**Comment by jennybc** [comment] 2021-10-04 16:27
I think this might be a bug in desc. Specifically in `desc$normalize()`. More, specifically, in `idesc_reformat_fields()`.

I think this code to temporarily turn crayon off is not working as intended:

https://github.com/r-lib/desc/blob/1a9af2d57b92de577e4cd67f126a4f1461554db6/R/str.R#L142-L143

``` r
Sys.setenv(R_CLI_NUM_COLORS = 256)
library(desc)

desc <- description$new(package = "usethis")
desc$get("Package")
#>   Package 
#> "usethis"
desc$normalize()
desc$get("Package")
#>                            Package 
#> "\033[34mPackage\033[39m: usethis"
```

<sup>Created on 2021-10-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by jennybc** [comment] 2021-10-04 16:29
(It's still possible that usethis should use `$write()`. But the problem all starts when we call `$normalize()`, which appears to build ANSI escapes into the actual data.

**Comment by gaborcsardi** [comment] 2021-10-04 16:47
Just fixed that. 

(Of course `Sys.setenv(R_CLI_NUM_COLORS = 256)` is also a bad idea.)

**Closed** 2021-10-07 22:00 UTC
Labels: description :books:
