### ISSUE TITLE
Ensure alphabetical order when adding a dependency with usethis

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/usethis#857] opened 2019-07-29 11:45 UTC
Problem: New dependency added with `use_package()` and `use_dev_package()` is added as last item in the respecive Field in DESCRIPTION. 

Easy fix:  should run `use_tidy_description()` on exit to make sure the added entry in DESCRIPTION is put in the right place. This will in general have unintended side effects with the formatting of DESCRIPTION.

Clean fix: Make sure you instert in the right place in the first place. 

What do you think?

**Comment by jennybc** [comment] 2019-07-29 14:30
Kind of a duplicate of #443

**Comment by jennybc** [comment] 2019-07-29 14:32
To be clear, my personal taste is also to alphabetize them and rigorously maintain that style.

**Comment by hadley** [comment] 2019-10-16 21:44
It's easiest to do this in desc, I think: https://github.com/r-lib/desc/pull/85

**Closed by hadley** 2019-10-16 21:44 UTC
Labels: description :books:, feature
