### ISSUE TITLE
Allow to use capital letters when using use_r

### ISSUE THREAD

**Issue by llrs** [r-lib/usethis#564] opened 2019-01-10 21:54 UTC
I was surprised that I couldn't create the AllGenerics.R file via the `use_r` function, because it converts all the names to lower case. The reason is that it uses `slug` calls `asciify` which converts everything to lower case:

https://github.com/r-lib/usethis/blob/02fc4b20f022b0b98afcb323ef770fd78c00ae5a/R/utils.R#L33

The tidyverse [naming conventions](https://style.tidyverse.org/files.html#names) recommend the "all-generics.R" style. But in other styles ([Bioconductor](https://bioconductor.org/developers/how-to/coding-style/)) it is recommended to use the CamelCase format for some files like this one. Perhaps `use_r` could allow file names in upper case too? (Maybe with a warning?)

I could submit a pull request (or leave it for the developer conference day) if you wish.

**Comment by hadley** [comment] 2019-01-23 20:54
Duplicate of #581 — a PR would definitely be appreciated.

**Closed by hadley** 2019-01-23 20:54 UTC
