### ISSUE TITLE
Continuing problems with document(): Files 'DESCRIPTION' and 'DESCRIPTION.in' are missing.

### ISSUE THREAD

**Issue by shirewoman2** [r-lib/usethis#1840] opened 2023-05-16 03:43 UTC
I would like to re-open this issue: [[BUG] Issue in document(): Files 'DESCRIPTION' and 'DESCRIPTION.in' are missing.](https://github.com/r-lib/devtools/issues/2512)

Just like @jmrothen, after using devtools::document() to create the documentation for my package, when I try looking at the help file for one of my package functions, I get this error: 
`Error in .get_package_metadata(pkgdir) : 
  Files 'DESCRIPTION' and 'DESCRIPTION.in' are missing.`

This is a problem on the machine I use with R version 4.3.0 but works fine on a machine I use with R 4.2.3. I'm using devtools version 2.4.5. Unlike @jmrothen, I was not able to resolve the problem by re-creating all my man pages or by removing and then remaking my package's DESCRIPTION file.

**Comment by ateucher** [comment] 2023-05-16 16:50
Thanks! This looks like an RStudio IDE issue, and it appears they have fixed it in development: https://github.com/rstudio/rstudio/issues/12945

**Comment by ateucher** [comment] 2023-05-16 16:54
I just installed the daily RStudio build (https://dailies.rstudio.com/) and it appears to be fixed there (I was able to reproduce the issue in the current released version).

**Comment by jennybc** [comment] 2023-05-16 17:59
Thanks @ateucher for connecting the dots. I'm closing since it seems pretty clear it's not a usethis (or devtools) issue.

**Closed by jennybc** 2023-05-16 17:59 UTC

**Comment by shirewoman2** [comment] 2023-05-16 20:13
Thanks for looking into this! Yes, when I installed the daily RStudio build, the problem was solved.
