### ISSUE TITLE
create_from_github(open=TRUE) fails on RStudio-server

### ISSUE THREAD

**Issue by cboettig** [r-lib/usethis#115] opened 2017-11-20 17:04 UTC
another minor thing from #109

Looks like you use `utils::browse()` to open the .Rproj file if the user is using RStudio... guessing this does the right thing in the desktop but in RStudio-server this literally opens the `.Rproj` as a plain text file in the browser.

**Comment by jennybc** [comment] 2018-01-15 00:12
Duplicate of #129

**Closed by jennybc** 2018-01-15 00:12 UTC
