### ISSUE TITLE
should git_ask_commit() check the project uses git?

### ISSUE THREAD

**Issue by maelle** [r-lib/usethis#550] opened 2018-12-13 15:30 UTC
I've just gotten the error message

```r
Error: Cannot detect that project is already a Git repository.
Do you need to run `use_git()`?
```
whilst running `use_news_md()` before `use_git()`. In my use case, the `pRojects` package, we create a bunch of things before creating the git repo, so I'd like `git_ask_commit()` to have a condition on `uses_git()` similar to the interactive condition.

Would you be interested in a pull request for this or should I rather write a workaround in `pRojects`? Thanks!

**Comment by jennybc** [comment] 2018-12-13 17:34
Duplicate of #523

**Closed by jennybc** 2018-12-13 17:34 UTC

**Comment by maelle** [comment] 2018-12-13 18:16
Oh I had missed that sorry. I think you meant #532
