### ISSUE TITLE
New feature: use_data_doc() for creating roxygen documentation of a dataset

### ISSUE THREAD

**Issue by friendly** [r-lib/usethis#1896] opened 2023-09-21 21:06 UTC
I’ve long been miffed by the inability to document data sets in R packages using roxygen style. Just as in RStudio, you can highlight a function and select Code -> Insert roxygen skeleton, there should be something, somewhere for data sets.

I wrote and documented a new function, `use_data_doc()`, as a gist: https://gist.github.com/friendly/14f3ee1464213bb0b9fbcb489468383b 

That was assuming it might find a place in the usethis package, perhaps with a different name.

My translation from `utils::promptData()` was fairly simple.

I've raised this question on the r-pkg-devel list if you want to look at that discussion.

**Comment by jennybc** [comment] 2024-07-22 23:11
This is basically a duplicate of #1681, where there has already been a fair bit of discussion. So closing this in favor of #1681, but now they are linked.

**Closed by jennybc** 2024-07-22 23:11 UTC
Labels: feature, code :desktop_computer:
