### ISSUE TITLE
`use_github_release()` should not completely melt down in the absence of NEWS

### ISSUE THREAD

**Issue by kivanvan** [r-lib/usethis#1878] opened 2023-07-21 19:19 UTC
I am using the `use_github_release()` to release my package on GitHub. I got the 

> Error in value[[3L]](cond) : attempt to apply non-function

 after it tries to 

> Pushing local 'master' branch to 'origin/master'.

 I am not sure what goes wrong in the release process. 

I was following the steps from `use_release_issue()`. The only thing I didn't do is to create a news file, which I think is not necessary as it's the initial version of my package. Is this causing the error I got?

**Comment by jennybc** [comment] 2023-07-21 19:25
It shouldn't fail in such a gross way 😬 , but, yes, your suspicion about the lack of a NEWS file is probably correct. We make the release's description from items found in the NEWS file and this is exactly why it's in the checklist. We have tried this many different ways (where to sequence the creation of the initial NEWS file) and have settled on this as the least bad solution.

**Comment by kivanvan** [comment] 2023-07-21 19:30
Does it work if I create a news file now? I assume that then I need to resubmit to CRAN for this change, right?

**Comment by jennybc** [comment] 2023-07-21 22:02
No, this has nothing to with CRAN. But no it won't help usethis get unstuck to create a NEWS file now, because it's looking for NEWS in the git commit (state) that you submitted to CRAN. The die is cast.

But you might be able to do `debug(use_github_release()` (or just read/execute it's source selectively) to resolve the current release. Once you have a NEWS file, this will never happen again.

**Comment by kivanvan** [comment] 2023-07-24 15:46
Gotcha, thanks a lot!

**Comment by kivanvan** [comment] 2023-07-24 17:09
Okay, I have manually released my package on GitHub. But let me know if you need any information from my end.

**Comment by GuiFabre** [comment] 2023-08-15 17:33
Hi @jennybc and @kivanvan . I'm facing the same issue. I will manually create the git_hub release and add a NEWS.md for the future submissions to CRAN.

**Comment by thomascwells** [comment] 2024-08-15 20:39
At tidy-dev-day today I tried to reproduce this using the steps below, but I couldn't get an error. It's possible this error addressed in another PR or that my steps to reproduce are incomplete. Let me know if there's something else I should try or if anyone has steps for a more complete reprex. 

1. fork the usethis repo
3. delete the NEWS.md file
5. update the description release number to something new
4. commit, and push to main on my fork. 
7. run `use_github_release()`

Here's the output from that last step.

```
> use_github_release()
Which repo should we target? 

1: thomascwells/usethis = "origin"
2: r-lib/usethis = "upstream"

Selection: 1
✔ Using current HEAD commit for the release.
✔ Checking that remote branch "origin/main" has the changes in "main".
• Release name: "usethis 3.0.0.9004"
• Tag name: "v3.0.0.9004"
• SHA: "e398ee4905884290804d81651eeb9270acaf2242"
✔ Pushing local "main" branch to "origin/main".
✖ Can't find NEWS.md in the released package source.
ℹ usethis consults this file for release notes.
ℹ Call usethis::use_news_md() to set this up for the future.
Publishing v3.0.0.9004 release to GitHub
Release at <https://github.com/thomascwells/usethis/releases/tag/v3.0.0.9004>
```

The message about "Can't find NEWS.md ... " suggests it's looking for the file, sees that it's missing, but doesn't fail as described earlier.

**Comment by jennybc** [comment] 2024-08-15 21:22
I guess this has been solved since this issue was opened? In any case we will close it and see if someone can present us with a new reprex.

**Closed by jennybc** 2024-08-15 21:22 UTC
Labels: bug, tidy-dev-day :nerd_face:, release :flight_departure:
