### ISSUE TITLE
Add documentation to create_package() in existing project

### ISSUE THREAD

**Issue by angela-li** [r-lib/usethis#893] opened 2019-09-21 20:45 UTC
In the `create_package()` documentation, it mentions that you can create a package from an existing project. It would be useful to include an example in the function documentation of how to do this (I did it with `create_package(getwd())`). 

Adding this example in the `create_package()` function documentation would be helpful, especially if we are encouraging Github-first workflows!

**Comment by jennybc** [comment] 2019-10-01 00:29
(Sort of) a duplicate of #777. Closing this one, but they are now linked. When this functionality gets restored, we should also make sure there's a relevant example. I prefer to make `create_package()` or `create_package(".")` work (again), as opposed to featuring `getwd()`. As a matter of policy, I try to downplay `getwd()` and `setwd()`. (But it's true that right now you have to do this via `create_package(getwd())` but that shouldn't be required.

**Closed by jennybc** 2019-10-01 00:29 UTC
